name: "Jarvis Assistant"
version: "1.0.20"
slug: "jarvis_assistant"
description: "A local, private voice assistant using Piper TTS and Porcupine."
url: "https://github.com/Iron-Matrix4/ha-addons/tree/master/jarvis_assistant"
startup: application
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
options:
  gemini_api_key: ""
  picovoice_access_key: ""
schema:
  gemini_api_key: str
  picovoice_access_key: str
ports:
  10200/tcp: 10200 # Wyoming port (future)
